### ISSUE TITLE
Wrong URL

### ISSUE THREAD

**Issue by san-pok** [thapatechnical/WorldBestJSCourse#2]
Hi guys, accidentally there is a wrong URL being pasted , although that was to try the try and catch, on promises.html file which is located under adVancedJS>functions>promises.html: pasted url:  const apiUrl = "https://icanhazdadjoke.cosm/";    corrected version:  const apiUrl = "https://icanhazdadjoke.com/";

so if your code is not running in the initial phase before staring the try and catch section  please fix this (just remove the s from cosm and make it .com) and also run your file through live server to avoid any CORS related issues.

**Comment by thapatechnical** [comment]
Thank you you so much. I updated the code and already push so now I guess there will be no issue.

**Comment by thapatechnical** [comment]
Issue resolved. Closing now. Thanks!

**Comment by DushyantSharma08** [comment]
event folder missing
